<?php
include('partials/_head.php');
include('partials/_headerWrapper.php');
include('partials/_bannerWrapper.php');
include('partials/_featuresWrapper.php');
include('partials/_mainWrapper.php');
include('partials/_footerWrapper.php');
include('partials/_end.php');
?>